name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LANG: pt_BR.UTF-8
      LANGUAGE: pt_BR:pt
      LC_ALL: pt_BR.UTF-8

    steps:
      - uses: actions/checkout@v4

      - name: Install pt-BR language pack
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-pt language-pack-pt-base
          sudo update-locale LANG=pt_BR.UTF-8

      - name: Export locale
        run: |
          echo "LANG=pt_BR.UTF-8" >> $GITHUB_ENV
          echo "LANGUAGE=pt_BR:pt:en" >> $GITHUB_ENV
          echo "LC_ALL=pt_BR.UTF-8" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (run tests)
        run: mvn clean install -DskipTests=false
